CREATE TABLE `alarm_irv_frame`
(
    `alarm_id`           VARCHAR(40),
    `frame_no`           INT,
    `raised_time`        DATETIME,
    `speed`              INT,
    `starnum`            INT,
    `scs_irvtemp`        INT,
    `scs_envtemp`        INT,
    `irv_irvtemp`        INT,
    `scs_stagger`        INT,
    `scs_lineheight`     INT,
    `stagger_cur`        INT,
    `stagger_o_name`     VARCHAR(20),
    `stagger_s_name`     VARCHAR(20),
    `stagger1`           INT,
    `irv_stagger1`       INT,
    `ob_stagger1`        INT,
    `tb_stagger1`        INT,
    `stagger2`           INT,
    `irv_stagger2`       INT,
    `ob_stagger2`        INT,
    `tb_stagger2`        INT,
    `stagger3`           INT,
    `irv_stagger3`       INT,
    `ob_stagger3`        INT,
    `tb_stagger3`        INT,
    `stagger4`           INT,
    `irv_stagger4`       INT,
    `ob_stagger4`        INT,
    `tb_stagger4`        INT,
    `hdindex`            INT,
    `oaindex`            INT,
    `obindex`            INT,
    `bowcenterx`         INT,
    `bowcentery`         INT,
    `matscale`           INT,
    `bow_bg_type`        INT,
    `alarm_monitor_rect` VARCHAR(50),
    `ecwire_prob`        INT,
    PRIMARY KEY (`alarm_id`, `frame_no`),
    KEY `ix_alarm_irv_frame_raised_time` (`raised_time`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
;