CREATE TABLE `mis_position`
(
    `id`                  varchar(128) NOT NULL,
    `position_code`       varchar(128) NOT NULL,
    `position_code_plus`  varchar(128),
    `position_type`       varchar(8),
    `line_code`           varchar(32),
    `direction`           varchar(20),
    `start_km`            decimal(16, 0),
    `end_km`              decimal(16, 0),
    `position_length`     varchar(16),
    `gis_lon_o`           double,
    `gis_lat_o`           double,
    `gis_lat`             double,
    `gis_lon`             double,
    `gis_show`            double,
    `usage_status`        varchar(20),
    `is_serious_polluted` varchar(20),
    `position_order`      double,
    `org_code`            varchar(128),
    `workshop_code`       varchar(128),
    `power_section_code`  varchar(128),
    `bureau_code`         varchar(32),
    `icon_path`           varchar(128),
    `note`                varchar(256),
    `opt_person`          varchar(128),
    `opt_time`            datetime,
    `opt_action`          varchar(32),
    `opt_ip`              varchar(32),
    `opt_id`              varchar(128),
    `opt_context`         varchar(256),
    `is_modify_allowed`   varchar(8),
    `trcs_num`            double,
    PRIMARY KEY (`position_code`) USING BTREE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
