CREATE TABLE `mis_pole`
(
    `id`                   varchar(128) NOT NULL,
    `pole_code`            varchar(50)  NOT NULL,
    `pole_no`              varchar(128),
    `pole_direction`       varchar(20),
    `pole_type`            varchar(20),
    `pole_order`           double,
    `md_code`              varchar(128),
    `substation_code`      varchar(100),
    `substation_name`      varchar(50),
    `brg_tun_code`         varchar(50),
    `brg_tun_name`         varchar(50),
    `position_code`        varchar(50),
    `position_name`        varchar(50),
    `line_code`            varchar(128),
    `line_name`            varchar(50),
    `org_code`             varchar(100),
    `org_name`             varchar(50),
    `workshop_code`        varchar(100),
    `workshop_name`        varchar(50),
    `power_section_code`   varchar(100),
    `power_section_name`   varchar(50),
    `bureau_code`          varchar(100),
    `bureau_name`          varchar(50),
    `install_img_no`       varchar(50),
    `install_time`         datetime,
    `pole_usage`           varchar(20),
    `structure_height`     double,
    `geography_name`       varchar(30),
    `kmstandard`           decimal(16, 0),
    `side_limit_cx`        varchar(100),
    `pole_basic_type`      varchar(100),
    `wire_design_height`   double,
    `design_pulling_value` double,
    `gis_lon`              double,
    `gis_lat`              double,
    `gis_lon_o`            varchar(128),
    `gis_lat_o`            varchar(128),
    `proc_earthing_way`    varchar(20),
    `pole_img_c2`          varchar(500),
    `pole_img_c4`          varchar(500),
    `alarm_count`          double,
    `fault_count`          double,
    `span_length`          varchar(100),
    `poleno_c2`            varchar(128),
    `pole_img`             varchar(500),
    `pole_status`          varchar(20),
    `locating_method`      varchar(20),
    `note`                 varchar(500),
    `pole_zt_type`         varchar(100),
    `strong_line`          varchar(100),
    `protect_line`         varchar(100),
    `positive_feeder`      varchar(100),
    `curve_radius`         varchar(13),
    `railface_high`        varchar(13),
    `curve_direction`      varchar(100),
    `is_filled`            varchar(50),
    `wire_limit_height`    double,
    `limit_pulling_value`  double,
    `comps_proportion`     varchar(100),
    `pole_cls_bcbl`        varchar(100),
    `opt_person`           varchar(50),
    `opt_time`             datetime,
    `opt_action`           varchar(20),
    `opt_ip`               varchar(20),
    `opt_id`               varchar(32),
    `opt_context`          varchar(100),
    `is_modify_allowed`    varchar(8),
    `p_org_code`           varchar(50),
    `create_time`          datetime,
    `serial_no`            decimal(6, 0),
    `frame_no`             decimal(6, 0),
    `exception_data_type`  varchar(20),
    `km_trend`             decimal(1, 0),
    `ver_code`             varchar(40),
    `mcdesc`               varchar(200),
    `acdesc`               varchar(200),
    `dup_pole`             varchar(200),
    `dup_pw`               varchar(40),
    `track_code`           varchar(40),
    `org_direction`        varchar(10),
    `mdgj_id`              varchar(40),
    `mtr_qlt`              varchar(20),
    `mnft_fct`             varchar(100),
    `comms_date`           datetime,
    `prod_date`            datetime,
    `dsgn_life`            double,
    `pole_bsc_sts`         varchar(20),
    `grnd_sts`             varchar(20),
    `aux_has_bczz`         varchar(1),
    `aux_has_fdjyq`        varchar(1),
    `aux_has_fxjyq`        varchar(1),
    `aux_be_jcxc`          varchar(1),
    `aux_be_lxwjcxc`       varchar(1),
    `aux_be_sxwjcxc`       varchar(1),
    `aux_be_mdgjsdfx`      varchar(1),
    `aux_has_yhk`          varchar(1),
    `aux_has_dljx`         varchar(1),
    `aux_has_glkg`         varchar(1),
    `aux_has_blq`          varchar(1),
    `aux_has_dcgyzz`       varchar(1),
    `aux_has_xcbzp`        varchar(1),
    `aux_has_jdzz`         varchar(1),
    `aux_has_xsx`          varchar(1),
    `aux_has_hlx`          varchar(1),
    `aux_has_gwx`          varchar(1),
    `aux_has_gdx`          varchar(1),
    `aux_has_pwx`          varchar(1),
    `aux_has_afx`          varchar(1),
    `aux_has_jqx`          varchar(1),
    `aux_has_blz`          varchar(1),
    `aux_has_lx`           varchar(1),
    `aux_has_zm`           varchar(1),
    `aux_gq`               varchar(100),
    `aux_jxzq`             varchar(50),
    `pole_mdl`             varchar(20),
    PRIMARY KEY (`pole_code`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
