CREATE TABLE `nos_ac_pold`
(
    `ID`        VARCHAR(128) NOT NULL,
    `INPUTDATE` DATETIME DEFAULT NULL COMMENT 'date',
    `CONTENT`   TEXT COMMENT 'json'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
    PARTITION BY RANGE COLUMNS (INPUTDATE)
        (
        PARTITION p_20180101 VALUES LESS THAN ("2018-01-02")
        );