CREATE TABLE `mis_substation`
(
    `id`                 VARCHAR(128) NOT NULL,
    `substation_code`    VARCHAR(50)  NOT NULL,
    `substation_name`    VARCHAR(200),
    `substation_type`    VARCHAR(200),
    `substation_no`      VARCHAR(200),
    `gis_lat`            DECIMAL(16, 6),
    `gis_lon`            DECIMAL(16, 6),
    `monitor_place`      VARCHAR(200),
    `icon_path`          VARCHAR(200),
    `km_mark_sx`         DECIMAL(16, 0),
    `km_mark_xx`         DECIMAL(16, 0),
    `inf_version`        VARCHAR(100),
    `note`               VARCHAR(200),
    `position_code`      VARCHAR(128),
    `position_name`      VARCHAR(50),
    `line_code`          VARCHAR(128),
    `line_name`          VARCHAR(50),
    `org_code`           VARCHAR(100),
    `org_name`           VARCHAR(50),
    `workshop_code`      VARCHAR(100),
    `workshop_name`      VARCHAR(50),
    `power_section_code` VARCHAR(100),
    `power_section_name` VARCHAR(50),
    `bureau_code`        VARCHAR(100),
    `bureau_name`        VARCHAR(50),
    `is_modify_allowed`  VARCHAR(8),
    `tarea`              DECIMAL(10, 0),
    `bteara`             DECIMAL(10, 0),
    `pbeara`             DECIMAL(10, 0),
    `rmnum`              DECIMAL(10, 0),
    `fshd`               DATE,
    `ntkm`               DECIMAL(10, 0),
    `dvnum`              DECIMAL(10, 0),
    `pwmdl`              VARCHAR(200),
    `pwrng`              VARCHAR(200),
    `subkm`              DECIMAL(10, 0),
    `bsdesc`             VARCHAR(500),
    `asst_dptmt`         VARCHAR(100),
    `nature`             VARCHAR(200),
    `rnno`               VARCHAR(60),
    `rnnm`               VARCHAR(60),
    `insdate`            DATE,
    `optdate`            DATE,
    `optsts`             VARCHAR(60),
    `recq`               DECIMAL(10, 0),
    `speq`               DECIMAL(10, 0),
    `treq`               DECIMAL(10, 0),
    `ntreq`              DECIMAL(10, 0),
    `sueq`               DECIMAL(10, 0),
    `inpfnm`             VARCHAR(60),
    `inpfpnm`            VARCHAR(60),
    `rvtg`               DECIMAL(10, 0),
    `vtgdgr`             VARCHAR(60),
    `inpfmdl`            VARCHAR(60),
    `inpflen`            DECIMAL(10, 0),
    `inpsnm`             VARCHAR(60),
    `inpspnm`            VARCHAR(60),
    `inpsmdl`            VARCHAR(60),
    `inpslen`            DECIMAL(10, 0),
    `fdfnm`              VARCHAR(60),
    `fdfno`              VARCHAR(60),
    `fdsnm`              VARCHAR(60),
    `fdsno`              VARCHAR(60),
    `fdsdnm`             VARCHAR(60),
    `fdsdno`             VARCHAR(60),
    `fdthnm`             VARCHAR(60),
    `fdthno`             VARCHAR(60),
    `uskm`               DECIMAL(10, 0),
    `uekm`               DECIMAL(10, 0),
    `dskm`               DECIMAL(10, 0),
    `dekm`               DECIMAL(10, 0),
    `stdrt`              VARCHAR(60),
    `inpfpcd`            VARCHAR(60),
    `inpspcd`            VARCHAR(60),
    `gis_lon_o`          DECIMAL(16, 6),
    `gis_lat_o`          DECIMAL(16, 6),
    `direction`          VARCHAR(20),
    `dev_url`            VARCHAR(200),
    `subst_idno`         VARCHAR(30),
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;