CREATE TABLE `mis_task`
(
    `id`               varchar(128) NOT NULL,
    `task_code`        varchar(100),
    `pid`              varchar(128),
    `faultid`          varchar(128),
    `datatype`         varchar(10),
    `category_code`    varchar(10),
    `code`             varchar(20),
    `summary`          varchar(100),
    `severity`         varchar(10),
    `status`           varchar(20),
    `alarm_analysis`   varchar(512),
    `proposal`         varchar(512),
    `remark`           varchar(512),
    `fault_descript`   varchar(500),
    `task_descript`    varchar(256),
    `disposername`     varchar(100),
    `disposer`         varchar(128),
    `dispose_deptname` varchar(100),
    `dispose_dept`     varchar(128),
    `dispose_time`     datetime,
    `due_time`         datetime,
    `receiver`         varchar(128),
    `receivername`     varchar(128),
    `recv_dept`        varchar(128),
    `recv_deptname`    varchar(128),
    `deal_result`      varchar(256),
    `deal_descript`    varchar(256),
    `sponsor`          varchar(128),
    `sponsorname`      varchar(128),
    `sponsor_dept`     varchar(128),
    `sponsor_deptname` varchar(128),
    `sponsor_time`     datetime,
    `deadline`         datetime,
    `is_tel`           varchar(10),
    `is_mail`          varchar(10),
    `status_time`      datetime,
    `is_info`          varchar(10),
    `dealer`           varchar(128),
    `dealername`       varchar(128),
    `deal_dept`        varchar(128),
    `deal_deptname`    varchar(128),
    `deal_ticket`      varchar(128),
    `checker`          varchar(128),
    `checekrname`      varchar(128),
    `check_dept`       varchar(128),
    `check_deptname`   varchar(128),
    `check_descript`   varchar(128),
    `check_ticket`     varchar(128),
    `check_value`      varchar(128),
    `deal_time`        datetime,
    `deal_value`       varchar(128),
    `check_time`       datetime,
    `check_picture`    varchar(2000),
    `accepter`         varchar(128),
    `auditor`          varchar(128),
    `declarer`         varchar(128),
    `declare_time`     datetime,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
