CREATE TABLE `tsys_user`
(
    `id`               varchar(100) NOT NULL,
    `loginid`          varchar(100) NOT NULL,
    `password`         varchar(100),
    `person_code`      varchar(100),
    `role_code`        varchar(100),
    `user_code`        varchar(100) NOT NULL,
    `per_name`         varchar(30),
    `per_abbr`         varchar(20),
    `per_status`       varchar(30),
    `work_no`          varchar(30),
    `work_type`        varchar(30),
    `tel`              varchar(128),
    `email`            varchar(128),
    `sex`              varchar(30),
    `birthdate`        datetime,
    `addr`             varchar(255),
    `postcode`         varchar(10),
    `city`             varchar(60),
    `prov`             varchar(60),
    `country`          varchar(60),
    `duty`             varchar(60),
    `posttitle`        varchar(30),
    `employee_type`    varchar(30),
    `security_class`   varchar(128),
    `supervisor`       varchar(128),
    `org_code`         varchar(100),
    `dept_name`        varchar(100),
    `corp_code`        varchar(128),
    `corp_name`        varchar(128),
    `is_staffer`       varchar(10),
    `hire_date`        datetime,
    `end_hire_date`    datetime,
    `is_order`         double,
    `user_type`        varchar(4),
    `vcode`            varchar(30),
    `vexpire_time`     datetime,
    `allowmobilelogin` varchar(1),
    `appmainpage`      double DEFAULT '0',
    PRIMARY KEY (`loginid`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;
