CREATE TABLE `alarm_aux_pnew`
(
    `alarm_id`           VARCHAR(40) NOT NULL,
    `bmi_file_name`      TINYTEXT,
    `rpt_file_name`      TINYTEXT,
    `bow_offset`         DECIMAL(7, 2),
    `gps_body_direction` TINYTEXT,
    `img_body_direction` TINYTEXT,
    `reportwordurl`      TINYTEXT,
    `lock_person_name`   TINYTEXT,
    `lock_time`          DATETIME,
    `confidence_level`   TINYINT(4),
    `raised_time_aux`    DATETIME    NOT NULL,
    `is_abnormal`        TINYTEXT,
    `svalue6`            TEXT,
    `svalue7`            TEXT,
    `svalue10`           TEXT,
    `svalue12`           TEXT,
    `svalue13`           TEXT,
    `alarm_reason`       TEXT,
    `airesult`           TINYTEXT,
    `remark`             TEXT,
    `trans_info`         TEXT,
    `dev_name`           TINYTEXT,
    `station_name`       TINYTEXT,
    `process_deptname`   TINYTEXT,
    `report_deptname`    TINYTEXT,
    `plan_id`            VARCHAR(40),
    `plan_task_id`       VARCHAR(40),
    `process_date`       DATETIME,
    `process_details`    TINYTEXT,
    `process_overdue`    TINYTEXT,
    `process_person`     TINYTEXT,
    `process_type`       TINYTEXT,
    `profession_type`    TINYTEXT,
    `repaired_pic`       TINYTEXT,
    `repaired_status`    TINYTEXT,
    `repair_method`      TINYTEXT,
    `repair_org`         TINYTEXT,
    `repair_person`      TINYTEXT,
    `report_overdue`     TINYTEXT,
    `review_info`        TINYTEXT,
    `review_person`      TINYTEXT,
    `review_time`        DATETIME,
    `check_details`      TEXT,
    `check_person`       TINYTEXT,
    `check_result`       TEXT,
    `harddisk_manage_id` VARCHAR(40),
    `attachment`         TINYTEXT,
    `comp_code`          TINYTEXT,
    `comp_type`          TINYTEXT,
    `nvalue7`            INT(11),
    `nvalue9`            INT(11),
    `nvalue11`           INT(11),
    `nvalue12`           INT(11),
    `nvalue17`           INT(11),
    `nvalue18`           INT(11),
    `nvalue19`           INT(11),
    `nvalue20`           INT(11),
    `power_device_code`  TINYTEXT,
    `power_device_type`  TINYTEXT,
    `substation_code`    TINYTEXT,
    `map_add_ima`        TINYTEXT,
    `vi_add_ima`         TINYTEXT,
    `oa_add_ima`         TINYTEXT,
    KEY `alarm_id` (`alarm_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
    PARTITION BY RANGE COLUMNS (raised_time_aux)
        (PARTITION p_20180101 VALUES LESS THAN ('2018-01-02')
        );
